-- Export for the demo: financial-reports on DEV. READ-ONLY: a single SELECT. Generated by tools/make_dev_exports.sh
-- from reports/financial-reports/dataset.sql - do not edit by hand. Save the WHOLE result (not the first 20,000 rows shown on
-- screen) as demo/private-data/dev_financial-reports.csv, then run: python3 tools/private_to_json.py financial-reports demo/private-data/dev_financial-reports.csv
-- The result holds real figures: it goes to demo/private-data/, never into git. Never paste a password.
SELECT * FROM (
    WITH store AS (
        SELECT DISTINCT ON (m.store_id)
               m.store_id,
               m.location_code,
               coalesce(n.plaza_name, 'Plaza ' || split_part(split_part(m.description, ' : ', 3), ' ', 1)) AS plaza,
               upper(trim(substr(split_part(m.description, ' : ', 3), strpos(split_part(m.description, ' : ', 3), ' ') + 1))) AS brand
        FROM master.location_code_mappings m
        LEFT JOIN (SELECT ct_location, min(trim(location_name)) AS plaza_name
                   FROM master.netsuite_location_mapping
                   WHERE ct_location IS NOT NULL
                   GROUP BY ct_location) n ON n.ct_location = m.location_code
        ORDER BY m.store_id, m.location_code
    ), items AS (
        SELECT o.end_day::date AS day, o.store_id, CAST(NULL AS text) AS donation_item,
               CAST(NULL AS text) AS lottery_category, CAST(NULL AS text) AS lottery_type,
               sum(o.tax) AS hst, 0::numeric AS gift_card, 0::numeric AS donations, 0::numeric AS lottery_amount
        FROM master.pos_orders o
        GROUP BY 1, 2
        UNION ALL
        SELECT d.end_day::date, d.store_id, NULL, NULL, NULL, 0, sum(d.value_added_base_price), 0, 0
        FROM master.pos_order_details d
        WHERE lower(d.department_name) IN ('gift card', 'retail - gift card', 'tim card', 'gift cards')
          AND d.menu_item_name <> 'Card Fee'
        GROUP BY 1, 2
        UNION ALL
        SELECT d.end_day::date, d.store_id, d.kitchen_name, NULL, NULL, 0, 0, sum(d.value_added_base_price), 0
        FROM master.pos_order_details d
        WHERE d.department_name = 'Donations' OR d.menu_item_name = 'Camp Day Bracelet'
        GROUP BY 1, 2, 3
        UNION ALL
        SELECT d.end_day::date, d.store_id, NULL,
               CASE WHEN d.menu_item_name IN ('Lottery Redemption', 'Lottery Payout') THEN 'Redemptions' ELSE 'Sales' END,
               CASE WHEN d.department_name = 'Open Lottery' THEN 'Open lottery' ELSE d.department_name END,
               0, 0, 0, sum(d.value_added_base_price)
        FROM master.pos_order_details d
        WHERE d.department_name IN ('Instant Tickets', 'Open Lottery')
        GROUP BY 1, 2, 4, 5
        UNION ALL
        SELECT p.end_day::date, p.store_id, NULL, 'Redemptions', 'Redemptions', 0, 0, 0, -sum(p.payment_amount)
        FROM master.pos_order_paid_outs p
        GROUP BY 1, 2
    )
    SELECT i.day,
           coalesce(s.plaza, 'Store ' || i.store_id) AS plaza,
           coalesce(s.brand, '(not mapped)')        AS brand,
           i.store_id,
           i.donation_item,
           i.lottery_category,
           i.lottery_type,
           i.hst,
           i.gift_card,
           i.donations,
           i.lottery_amount
    FROM items i
    LEFT JOIN store s ON s.store_id = i.store_id
) d
