-- Export for the demo: sales-field-team on DEV. READ-ONLY: a single SELECT. Generated by tools/make_dev_exports.sh
-- from reports/sales-field-team/dataset.sql - do not edit by hand. Save the WHOLE result (not the first 20,000 rows shown on
-- screen) as demo/private-data/dev_sales-field-team.csv, then run: python3 tools/private_to_json.py sales-field-team demo/private-data/dev_sales-field-team.csv
-- The result holds real figures: it goes to demo/private-data/, never into git. Never paste a password.
SELECT * FROM (
    WITH plaza_rename (old_name, new_name) AS (
        VALUES ('New Castle TO S', 'Newcastle'), ('S. Tilbury ON S', 'Tilbury South'), ('N. Tilbury ON S', 'Tilbury North'),
               ('Dutton ON S', 'Dutton'), ('W. Lorne ON S', 'West Lorne'), ('N. Trenton ON S', 'Trenton North'),
               ('S. Trenton ON S', 'Trenton South'), ('Ingleside ON S', 'Ingleside'), ('N. Mallorytown ON S', 'Mallorytown North'),
               ('S. Mallorytown ON S', 'Mallorytown South'), ('Napanee ON S', 'Napanee'), ('Odessa ON S', 'Odessa'),
               ('Port Hope ON S', 'Port Hope'), ('Woodstock ON S', 'Woodstock'), ('Ingersoll TO S', 'Ingersoll'),
               ('King City ON S', 'King City'), ('Maple TO S', 'Maple'), ('N. Cambridge ON S', 'Cambridge North'),
               ('S. Cambridge ON S', 'Cambridge South'), ('Barrie ON S', 'Barrie'), ('Innisfil ON S', 'Innisfil')
    ), loc AS (
        SELECT DISTINCT m.store_id, m.host_location_id, trim(m.location_name) AS location_name, m.brand_name,
               lower(trim(m.rollout)) AS rollout,
               coalesce(r.new_name, trim(replace(trim(m.location_name), 'ON S', ''))) AS plaza_base,
               CASE upper(trim(m.brand_name))
                   WHEN 'NY FRIES' THEN 'NEW YORK FRIES' WHEN 'STARBUX' THEN 'STARBUCKS'
                   WHEN 'TIM HORTON''S' THEN 'TIM HORTONS' WHEN 'TIM H DRIVE THRU' THEN 'TIM HORTONS'
                   WHEN 'WENDY''S' THEN 'WENDYS'
                   ELSE upper(trim(m.brand_name))
               END AS brand
        FROM master.netsuite_location_mapping m
        LEFT JOIN plaza_rename r ON r.old_name = trim(m.location_name)
        WHERE m.host_location_id IS NOT NULL AND lower(trim(m.rollout)) IN ('yes', 'suspended')  -- any case: DEV holds 'yes' too
    ), lb AS (
        SELECT DISTINCT host_location_id, brand, upper(plaza_base || ' ' || brand) AS lb_name FROM loc
    ), facts AS (
        SELECT o.end_day::date AS day, l.host_location_id, l.brand,
               sum(o.net) AS net_sales, 0::numeric AS card_fees, count(o.order_id) AS transactions,
               0::numeric AS labour_hours
        FROM master.pos_orders o
        JOIN loc l ON l.store_id = o.store_id
        WHERE o.order_type_name::text <> 'Cash Drop'
        GROUP BY 1, 2, 3
        UNION ALL
        SELECT d.end_day::date, l.host_location_id, l.brand, 0, sum(d.value_added_base_price), 0, 0
        FROM master.pos_order_details d
        JOIN loc l ON l.store_id = d.store_id
        WHERE d.menu_item_name = 'Card Fee' AND l.brand_name ILIKE 'mark%' AND l.rollout = 'yes'
          AND d.end_day > timestamp '2022-04-01 00:15:00'
        GROUP BY 1, 2, 3
        UNION ALL
        SELECT p.pay_date::date, lb.host_location_id, lb.brand, 0, 0, 0, sum(p.hours)
        FROM master.employee_pay_summary p
        JOIN lb ON lb.lb_name =
            replace(replace(replace(upper(trim(p.location)), 'TRAVEL PLAZA ', ''), ' ONSITE', ''), 'NYF', 'NEW YORK FRIES')
        WHERE p.location NOT ILIKE '%resource%'
          AND p.pay_category IN ('OT1.5', 'Reg', 'Hol1.5')
          AND coalesce(p.job, '') NOT IN ('ASSOCIATE GM', 'GENERAL MANAGER', 'MANAGER IN TRAINING', 'OPERATIONS MANAGER',
                                          'BRAND MANAGER')
        GROUP BY 1, 2, 3
        UNION ALL
        SELECT t.dlh_date, lb.host_location_id, lb.brand, 0, 0, 0, sum(t.dlh)
        FROM master.temp_dlh t
        JOIN lb ON lb.lb_name = upper(trim(t.plaza) || ' ' || trim(t.brand))
        GROUP BY 1, 2, 3
    ), plaza AS (
        SELECT host_location_id, min(plaza_base) AS plaza_base
        FROM (SELECT host_location_id, plaza_base FROM loc UNION ALL VALUES (4606, 'Maple'), (3640, 'Newcastle')) x
        GROUP BY host_location_id
    )
    SELECT f.day,
           trim(dt.weekday)                                              AS weekday,
           dt.day_of_week                                                AS weekday_no,
           dt.end_of_week                                                AS week_end,
           CASE WHEN p.plaza_base IN ('Bainsville', 'Morrisburg') THEN p.plaza_base || ' ON S' ELSE p.plaza_base END AS plaza,
           f.brand,
           dd.district_director,
           NULL::text                                                    AS agm,  -- OPEN 1: list not in the extract
           f.net_sales,
           f.card_fees,
           f.net_sales - f.card_fees                                     AS sales,
           f.transactions,
           f.labour_hours
    FROM facts f
    LEFT JOIN plaza p ON p.host_location_id = f.host_location_id
    LEFT JOIN master.date_table dt ON dt.date = f.day
    LEFT JOIN (SELECT host_location_id, min(district_director) AS district_director
               FROM master.district_directors GROUP BY host_location_id) dd ON dd.host_location_id = f.host_location_id
) d
