-- Export for the demo: waste-report on DEV. READ-ONLY: a single SELECT. Generated by tools/make_dev_exports.sh
-- from reports/waste-report/dataset.sql - do not edit by hand. Save the WHOLE result (not the first 20,000 rows shown on
-- screen) as demo/private-data/dev_waste-report.csv, then run: python3 tools/private_to_json.py waste-report demo/private-data/dev_waste-report.csv
-- The result holds real figures: it goes to demo/private-data/, never into git. Never paste a password.
SELECT * FROM (
    WITH loc AS (
        SELECT DISTINCT ct_location, location_name, brand_name, host_location_id
        FROM master.netsuite_location_mapping
        WHERE host_location_id IS NOT NULL AND lower(trim(rollout)) IN ('yes', 'suspended')  -- any case: DEV holds 'yes' too (King City TIM03)
    )
    SELECT w.period,
           loc.location_name                                    AS plaza,
           upper(replace(loc.brand_name, 'Wendy''s', 'WENDYS')) AS brand,
           dd.district_director,
           p.category,
           p.sub_category,
           concat(w.product_num, '-', p.product_name)           AS item_description,
           w.unit_price,
           w.begin_value,
           w.purchase_value,
           w.var_adj_value,
           w.end_value,
           w.transfer_out_value,
           w.cogs,
           w.theo_cost,
           w.waste_value,
           CASE WHEN coalesce(w.start_date, w.period) < date '2023-05-28' THEN 0 ELSE w.inv_adj_value END AS waste_adj_value
    FROM master.weekly_cogs w
    JOIN loc ON loc.ct_location = w.loc_code
    LEFT JOIN master.weekly_cogs_prod_num p ON p.product_num = w.product_num
    LEFT JOIN master.district_directors dd ON dd.host_location_id = loc.host_location_id
) d
