#!/usr/bin/env bash
# Builds one READ-ONLY export query per report in tools/dev_export/, from each report's dataset.sql, so the export
# always matches the report. Run it again after changing a dataset.sql.
# The user runs each file on DEV (kios_etl) and saves the result as demo/private-data/dev_<report>.csv, then runs
#   python3 tools/private_to_json.py <report> demo/private-data/dev_<report>.csv
# which writes demo/private-data/<report>.json for the dashboard. Nothing in demo/private-data/ goes into git.
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
for r in tender-report waste-report market-category sales-margin-budget sales-report-1 sales-budget-2026 sales-field-team financial-reports; do
  out="$HERE/tools/dev_export/$r.sql"
  {
    echo "-- Export for the demo: $r on DEV. READ-ONLY: a single SELECT. Generated by tools/make_dev_exports.sh"
    echo "-- from reports/$r/dataset.sql - do not edit by hand. Save the WHOLE result (not the first 20,000 rows shown on"
    echo "-- screen) as demo/private-data/dev_$r.csv, then run: python3 tools/private_to_json.py $r demo/private-data/dev_$r.csv"
    echo "-- The result holds real figures: it goes to demo/private-data/, never into git. Never paste a password."
    if [ "$r" = tender-report ]; then
      # One row per payment: add up per day / plaza / brand / payment type to keep the file small.
      echo "SELECT end_day, plaza, brand, district_director, payment_type, sequence,"
      echo "       sum(tender_amount) AS tender_amount, sum(paidout_amount) AS paidout_amount"
      echo "FROM ("
      # Full-line comments are left out: shorter text, and nothing for a SQL editor to mis-split on.
      grep -v '^[[:space:]]*--' "$HERE/reports/$r/dataset.sql" | sed 's/^/    /' 
      echo ") d"
      echo "GROUP BY end_day, plaza, brand, district_director, payment_type, sequence"
      echo "ORDER BY end_day, plaza, brand, sequence"
    else
      echo "SELECT * FROM ("
      # Full-line comments are left out: shorter text, and nothing for a SQL editor to mis-split on.
      grep -v '^[[:space:]]*--' "$HERE/reports/$r/dataset.sql" | sed 's/^/    /' 
      echo ") d"
    fi
  } > "$out"
  echo "wrote ${out#$HERE/}"
done
