#!/usr/bin/env bash
# Builds one READ-ONLY export query per report in tools/dev_export/, from each report's dataset.sql, so the export
# always matches the report. Run it again after changing a dataset.sql.
# The user runs each file on DEV (kios_etl), saves the result as CSV named dev_<report>.csv and attaches it.
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
for r in tender-report financial-reports sales-report-1 sales-margin-budget waste-report; do
  out="$HERE/tools/dev_export/$r.sql"
  {
    echo "-- Export for the demo: $r on DEV. READ-ONLY: a single SELECT. Generated by tools/make_dev_exports.sh"
    echo "-- from reports/$r/dataset.sql - do not edit by hand. Save the result as dev_$r.csv and attach it in the chat."
    echo "-- The result holds real figures: it goes to demo/private-data/, never into git. Never paste a password."
    if [ "$r" = tender-report ]; then
      # One row per payment: add up per day / plaza / brand / payment type to keep the file small.
      echo "SELECT end_day, plaza, brand, district_director, payment_type, sequence,"
      echo "       sum(tender_amount) AS tender_amount, sum(paidout_amount) AS paidout_amount"
      echo "FROM ("
      sed 's/^/    /' "$HERE/reports/$r/dataset.sql"
      echo ") d"
      echo "GROUP BY end_day, plaza, brand, district_director, payment_type, sequence"
      echo "ORDER BY end_day, plaza, brand, sequence"
    else
      echo "SELECT * FROM ("
      sed 's/^/    /' "$HERE/reports/$r/dataset.sql"
      echo ") d"
    fi
  } > "$out"
  echo "wrote ${out#$HERE/}"
done
